name: Build Pub Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  get-latest-version:
    uses: jesuscorral/resuable-workflows/.github/workflows/get-latest-version-docker-image.yml@main
    with:
      repository_name: pub
      namespace: jesuscorral
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
  
  increase-version:
    needs: get-latest-version
    uses: jesuscorral/resuable-workflows/.github/workflows/increase-version.yml@main
    with:
      current_version: ${{ needs.get-latest-version.outputs.current_version }}

  build-docker-image:
    needs: increase-version
    uses: jesuscorral/resuable-workflows/.github/workflows/build-push-docker-image.yml@v1.0.2
    with:
      repository_name: pub
      namespace: jesuscorral
      version: ${{ needs.increase-version.outputs.new_version }}
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
    
